### ISSUE TITLE
ArrayList<String> to List without parameter type using sonar:ArrayDesignatorOnType

### ISSUE THREAD

**Issue by jordiponsllaurado** [walkmod/walkmod-sonar-plugin#1]
If I have this piece of code
`ArrayList<String> titles = (ArrayList<String>) inTitles.clone();`
`String title = titles.get(0);`
`titles.remove(0);`

The plugin applies this transformation
`        List              titles = (ArrayList<String>) inTitles.clone();`
`        String title = titles.get(0);`
`        titles.remove(0);`

Which prevents the code to compiling because the list parameter type is missing.

I think that it should be something like:
`List<String> titles = (ArrayList<String>) inTitles.clone();`
`String title = titles.get(0);`
`titles.remove(0);`

**Comment by rpau** [comment]
Hi,

Can you tell me which is the transformation that are you applying? It is a sonar one, right?

**Comment by jordiponsllaurado** [comment]
I'm applying this:
`<transformation type="sonar:ArrayDesignatorOnType"/>`

**Comment by rpau** [comment]
Ok, thanks.

**Comment by rpau** [comment]
This is the only transformation that you apply? Because I have created a test and it does not modify that code.

**Comment by jordiponsllaurado** [comment]
This is my walkmod.xml

<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd">
<walkmod>
    <chain name="default">
        <transformation type="dead-code-cleaner"/>
        <transformation type="sonar:AddCurlyBrackets"/>
        <transformation type="sonar:AddSwitchDefaultCase"/>
        <transformation type="sonar:ArrayDesignatorOnType"/>
        <transformation type="sonar:CollapsibleIfStatements"/>
        <transformation type="sonar:DeclarationsShouldUseCollectionInterfaces"/>
        <transformation type="sonar:PrimitiveInstantiationForToString"/>
        <transformation type="sonar:RedundantCastsShouldNotBeUsed"/>
        <transformation type="sonar:RemoveCodeComment"/>
        <transformation type="sonar:RemoveEmptyMethod"/>
        <transformation type="sonar:RemoveEmptyStatement"/>
        <transformation type="sonar:RemoveLiteralBoolean"/>
        <transformation type="sonar:RemoveUnusedMethodParameters"/>
        <transformation type="sonar:RemoveUselessImports"/>
        <transformation type="sonar:RemoveUselessParentheses"/>
        <transformation type="sonar:RemoveUselessVariables"/>
        <transformation type="sonar:StaticInitializedFieldToFinal"/>
        <transformation type="sonar:StringCheckOnLeft"/>
        <transformation type="sonar:UseCollectionIsEmpty"/>
        <transformation type="sonar:UseStringEquals"/>
        <transformation type="sonar:VariableImmediatelyReturned"/>
        <writer path="src/main/java" type="javalang:string-writer"/>
    </chain>
</walkmod>

**Comment by rpau** [comment]
I can't see anything :)

**Comment by rpau** [comment]
I think I get the point about what is happening :P

**Comment by jordiponsllaurado** [comment]
ok I attached a txt with my xml :D

**Comment by rpau** [comment]
thanks a lot!

**Comment by rpau** [comment]
Hi I have fixed both issues, and I have deployed a new jar into the maven. If you run walkmod again in 1-2 hours, the problems should disappear.
