### ISSUE TITLE
Sample walkmod-sonar-plugin usage with maven

### ISSUE THREAD

**Issue by drik** [walkmod/walkmod-sonar-plugin#13]
Hi; can u please provide a sample usage of this plugin together with maven. I mean a walkmod.xml file

**Comment by rpau** [comment]
you do not need a walkmod.xml file for this. You can do it simply by running:

`walkmod apply -DauthToken="THIS_IS_MY_TOKEN" -DsonarHost="https://sonarqube.com" sonar`
