### ISSUE TITLE
sonar:RemoveUselessParentheses compilation error after doing a walkmod apply

### ISSUE THREAD

**Issue by jordiponsllaurado** [walkmod/walkmod-sonar-plugin#2]
I have a project that contains this line of code (is not pretty, I know :disappointed:   ):
`boolean dimensionsMatches = !(((yEnd1 <= yOrigin2) || (xEnd1 <= xOrigin2)) || ((yEnd2 <= yOrigin1) || (xEnd2 <= xOrigin1)));`

After executing walkmod I get this:
`boolean dimensionsMatches = !        yEnd1 <= yOrigin2 || xEnd1 <= xOrigin2 || yEnd2 <= yOrigin1 || xEnd2 <= xOrigin1;`

That it doesn't compile as it tries to do the `!` into an `int` instead of a `boolean`

This is my wakmod xml: 
[walkmode.txt](https://github.com/walkmod/walkmod-sonar-plugin/files/197274/walkmode.txt)

I think the problem is related with this transformation: sonar:RemoveUselessParentheses

**Comment by rpau** [comment]
Ok, thanks! I am going to create a test and fix it :)
